//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Видео_к_демоэкзамену.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int ID { get; set; }
        public int IDStudents { get; set; }
        public int IDDiscipline { get; set; }
        public int Evaluation { get; set; }
        public int IDNameGroup { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual NameGroup NameGroup { get; set; }
        public virtual Student Student { get; set; }
    }
}
